### PR TITLE
fix(quoi-feur): quoi-feur with edited messages

### PR DESCRIPTION
**Pull request by adfaure**
The bot detects *quoi(s)* when the user edits the message.

### CODE REVIEW

**Review by neolectron — APPROVED** [review]

**Comment by adfaure** [comment]
Don't merge. 
If we edit the same message several times, the bot can add a "coubeh" to "feur" leading to an inconsistent state.

**Comment by adfaure** [comment]
That should work now. Hopefully.

**Comment by neolectron** [comment]
Hello, is this still in "wip" or ready for review (because the tag is still here) ?

**Comment by adfaure** [comment]
Should be ready.

**Review by neolectron — APPROVED** [review]

**Pull request merged**
